name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Update Dev.to blog posts
      - name: Update README with Dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "DEVTO-BLOG-LIST"
          feed_list: "https://dev.to/feed/mtwn105"
          max_post_count: 5
          template: "- ğŸš€ **[$title]($url)**  \nğŸ“… *Published on $date*"
          date_format: "mmm dd, yyyy"

      # Update Medium blog posts
      - name: Update README with Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM-BLOG-LIST"
          feed_list: "https://medium.com/feed/@mtwn105"
          max_post_count: 5
          template: "- ğŸ“š **[$title]($url)**  \nğŸ“… *Published on $date*"
          date_format: "mmm dd, yyyy"

      # # Update Personal blog posts
      # - name: Update README with Personal blog posts
      #   uses: gautamkrishnar/blog-post-workflow@v1
      #   with:
      #     comment_tag_name: "BLOG-POST-LIST:blog.amitwani.dev"
      #     feed_list: "https://blog.amitwani.dev/rss.xml"
      #     max_post_count: 5
      #     template: "- ğŸŒŸ **[$title]($url)**<br/>ğŸ“… *Published on $date* | ğŸ·ï¸ $categories | â±ï¸ $readTime min read"
      #     date_format: "mm ddd yyyy"
      #     custom_tags: "categories,readTime"

      # Update YouTube videos
      - name: Update README with YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE-BLOG-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPV2VEOaixGCyYIthfjtMOg"
          max_post_count: 5
          template: "- ğŸ¥ **[$title]($url)**  \nğŸ“… *Uploaded on $date*"
          date_format: "mmm dd, yyyy"
