name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Update Dev.to blog posts
      - name: Update README with Dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "DEVTO-BLOG-LIST"
          feed_list: "https://dev.to/feed/mtwn105"
          max_post_count: 5
          template: '<tr><td>üöÄ <a href="$url">$title</a></td><td>$date</td></tr>'
          date_format: "mmm dd, yyyy"

      # Update Medium blog posts
      - name: Update README with Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM-BLOG-LIST"
          feed_list: "https://medium.com/feed/@mtwn105"
          max_post_count: 5
          template: '<tr><td>üìö <a href="$url">$title</a></td><td>$date</td></tr>'
          date_format: "mmm dd, yyyy"

      # # Update Personal blog posts
      # - name: Update README with Personal blog posts
      #   uses: gautamkrishnar/blog-post-workflow@v1
      #   with:
      #     comment_tag_name: "BLOG-POST-LIST:blog.amitwani.dev"
      #     feed_list: "https://blog.amitwani.dev/rss.xml"
      #     max_post_count: 5
      #     template: "- üåü **[$title]($url)**<br/>üìÖ *Published on $date* | üè∑Ô∏è $categories | ‚è±Ô∏è $readTime min read"
      #     date_format: "mm ddd yyyy"
      #     custom_tags: "categories,readTime"

      # Update YouTube videos
      - name: Update README with YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE-BLOG-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPV2VEOaixGCyYIthfjtMOg"
          max_post_count: 5
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          template: '<tr><td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td><td><a href="$url">$title</a><br/>$date</td></tr>'
          date_format: "mmm dd, yyyy"
